   Name           Domain             Range
   ----------------------------------------
   mult           <.1,.1>            .2
   mult           <.3,.3>            .4
   mult           <.5,.5>            .6
   mult           <.7,.8>            .9
   ----------------------------------------
   mult           <.4,.4>            .10
   mult           <.6,.6>            .11
   mult           <.2,.12>           .13
   ----------------------------------------
   mult           <.11,.11>          .14
   mult           <.10,.15>          .16
   add            <.9,.13>           .17
   ----------------------------------------
   mult           <.14,.18>          .19
   ----------------------------------------
   add            <.16,.19>          .20
   ----------------------------------------
   add            <.17,.20>          .21
   ----------------------------------------

 Directions -  <in,<in,<in,in>,<in,in>,<in,in>>> ~ out

 Wiring -  <.7,<.8,<.1,.12>,<.3,.15>,<.5,.18>>> ~ .21

 Inputs -  .7 .8 .1 .12 .3 .15 .5 .18
